Sprint 2
Pigulevskayas/middle.messenger.praktikum.yandex pull request #4
Opened 2021-09-18 20:37 UTC by Pigulevskayas

2021-09-20 19:57 UTC, bhoodream requested changes
Хорошая работа! Но есть и над чем поработать. :) Помимо комментариев по коду, столкнулся также со следующими проблемами:
- [ ] навигация
    - [ ] кнопка назад из профиля ведет на /index , такой страницы нет и пользователь видит пустой экран
- [ ] билд:
    - [ ] npm run build падает с ошибкой Build failed. Error: External modules are not supported when building for browser
- [ ] netlify 
    - [ ] проект недоступен по ссылке https://competent-varahamihira-4993c3.netlify.app/ , все страницы 404 ошибка
- [ ] структура проекта
    - [ ] папка `/src` должна лежать в корне проекта
    - [ ] все исходники должны лежать в `/src`
- [ ] валидация:
    - [ ] нет валидации на `focus/blur`
    - [ ] ошибка при валидации в формах при клике по кнопке: Uncaught TypeError: Cannot read properties of undefined (reading 'length')

2021-09-20 19:57 UTC, bhoodream commented on index.ts
> +  // root.innerHTML = '';
Комменты необходимо удалять, чтобы не засорять кодовую базу.

2021-09-20 19:57 UTC, bhoodream commented on index.ts
> +console.log(path)
Логи желательно убирать, чтобы не засорять консоль браузера.

2021-09-20 19:57 UTC, bhoodream commented on index.ts
> +  page = LoginPage;
Интересное выравнивание, обычно содержимое кейса также сдвигается для читабельности.

2021-09-20 19:57 UTC, bhoodream commented on index.ts
> +  render(".app", page);
`render(".app", page);` можно по идее сделать один раз в конце, таким образом не дублируя код в каждом кейсе.

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/chat-messages/index.ts
> +const pug = require('pug');
`pug` подключен, но никак здесь не используется, это мусор, такое нужно удалять, чтобы по возможности сохранять здоровый климат в кодовой базе :)

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/form/form.pug
> +div.auth__form
Этот блок было бы правильнее назвать более конкретно, что то типа `registerForm` или `authForm`.

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/form/form.ts
> +import EventBus from './event-bus.ts';
Что то странное в этом файле с отступами, до этого везде они были по 2 пробела, а здесь по 2 таба...

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/form/form.ts
> +		formItems.formElements.map(function(element: object){
Лучше использовать стрелочные функции в таких случаях: `(element: object) => { ... }`

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/modal/modal.css
> +  -webkit-box-align: center;
обычно для того чтобы вручную не прописывать все префиксы, используют плагины типа https://github.com/postcss/autoprefixer

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/modal/modal.css
> +  color: #f97c7c;
цвета и прочие брэнд атрибуты лучше хранить в переменных

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/modal/modal.html
> +
похоже это не просто `modal`, а что-то типа `avatarModal`. Точное именование позволяет сохранять порядок в проекте

2021-09-20 19:57 UTC, bhoodream commented on public/src/blocks/modal/prepros.config
> +{
Подскажи пожалуйста, зачем тебе `prepros` в проекте, если у тебя сборкой и прочим на данный момент занимается `parcel`?

2021-09-20 19:57 UTC, bhoodream commented on public/src/components/button/button.pug
> +button.button.auth__button #{text}
Любому `button` элементы нужен `type`, хорошая практика, для того чтобы браузер однозначно понимал назначение кнопки.

2021-09-20 19:57 UTC, bhoodream commented on public/src/components/input/input.pug
> +- var typeAttr = type
Такое ощущение что это клон компонента `public/src/components/input-message/input-message.pug`. Шаблоны для того и созданы, чтобы их можно было конфигурировать, мне кажется нужно попытаться переиспользовать этот компонент, во всех местах где нужен инпут.

2021-09-20 19:57 UTC, bhoodream commented on public/src/modules/fetch.ts
> +            if (method === 'GET' || !data) {
У тебя есть константа `METHODS.GET`

2021-09-20 19:57 UTC, bhoodream commented on public/src/pages/chat/chat.scss
> +	&__top {
Пустой селектор :)

2021-09-20 19:57 UTC, bhoodream commented on public/static/index.css
> +@import url('../src/pages/error/error.css');
В компонентом подходе предпочтительнее подключать стили внутри конкретных модулей, а не все скопом. Таким образом на странице будет использовать только тот код, который действительно в данный момент нужен.

2021-09-25 00:13 UTC, Pigulevskayas commented on public/src/blocks/modal/prepros.config
> +{
Привет! Начала сначала с верстки проекта на html + prepros, и он переехал в проект поэтому. на первом ревью не сделали замечание по этому поводу

2021-09-27 13:56 UTC, bhoodream approved these changes
Прекрасно! Не смею больше задерживать, желаю успехов в дальнейшей работе! АПРУВ!!!

2021-09-27 13:56 UTC, bhoodream commented on src/components/button/button.pug
> +button.button.auth__button(type="submit") #{text}
Вообще более распространенный тип просто `button`, но в формах часто используется именно `submit`. Можно было по идее подставлять сюда тип с помощью переменной, дефолтное значение которой `button`

2021-09-27 14:00 UTC, Pigulevskayas commented on src/components/button/button.pug
> +button.button.auth__button(type="submit") #{text}
Спасибо за подробное ревью!

2021-09-28 14:51 UTC, merged